### ISSUE TITLE
support IPAM

### ISSUE THREAD

**Issue by weizhoublue** [kubevirt/macvtap-cni#102]
in code implementation, it seems not to support IPAM field of the CNI configuration

does that make sense to support to call IPAM plugin ?

**Comment by maiqueb** [comment]
> in code implementation, it seems not to support IPAM field of the CNI configuration

Right, it doesn't. 

We've always thought of macvtap CNI as a way to connect directly the VMs to the physical networks running on the k8s nodes. Thus we always wanted to either use whatever DHCP infrastructure already available, or define static IPs via cloud-init.

Right now, I think supporting IPAM on these networks raises more questions than answers: what happens if there is an already available dhcp infra on said network for instance ? How does that play along w/ IPAM ?...

**Comment by weizhoublue** [comment]
here is a plan, maybe

the macvtap interface is inserted to virt-launcher pod , and the VM is assigned a interface by virtio. Currently, it should specify the static IP in the cloud-init. 

The problem raises when using static IPs.That seems to be hard to manage all VM IP address, and administrator maybe have to check IP conflict between existent VMs, and he also have to just ping the static IP in the subnet. so, the current implementation still could not ensure IP available, and hard to use in production envrionment

if the macvtap CNI support IPAM, maybe could help simplify the workflow.  When the macvtap interface got a IP address by the IPAM, kubevirt could help move its IP to the interface of the VM. Therefore, the IP of all VMs could be managed by IPAM components. 

so both the DHCP manner or IPAM manner could be easy to use

**Comment by weizhoublue** [comment]
I known the status, thanks and close the issue
